variable "project" {}
variable "env" {}
variable "ssh_key" {}
variable "public_subnets" {}
variable "vpc_id" {}
variable "instance_type" {}
variable "cw_alarm" {}
variable "comparison_operator" {}
variable "metric_name" {}
variable "name_space" {}
variable "alarm_description" {}
variable "lambda_function_name" {}
variable "python_runtime" {}